service:
  name: office-document-properties-skill

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  index:
    handler: index.handler
    name: DocumentPropertiesSkill
    runtime: nodejs8.10
    timeout: 120
    events:
      - http:
          method: POST
          path: DocumentPropertiesSkill
          cors: true
